name: Jekyll Site CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  JEKYLL_ENV: production
  BUNDLE_PATH: vendor/bundle
  BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jekyll/builder:latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - List files
        run: ls -la
        if: always()

      - name: Setup Ruby
        run: |
          echo "Ruby version: $(ruby -v)"
          echo "Bundler version: $(bundle -v)"
          bundle config path $BUNDLE_PATH
          bundle config deployment true
          bundle config clean true

      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3
          bundle list

      - name: Debug - Check Jekyll
        run: |
          jekyll --version
          jekyll doctor

      - name: Build with Jekyll (with retry)
        id: jekyll-build
        continue-on-error: false
        run: |
          set -x  # Enable debug output
          retry_count=0
          max_retries=2
          
          until [ $retry_count -ge $max_retries ]
          do
            jekyll build --trace --verbose && break
            retry_count=$((retry_count+1))
            echo "Build failed (attempt $retry_count/$max_retries), retrying..."
            sleep 5
          done
          
          if [ $retry_count -eq $max_retries ]; then
            echo "::error::Jekyll build failed after $max_retries attempts"
            exit 1
          fi

      - name: Upload artifact
        if: steps.jekyll-build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: ./_site
          retention-days: 1

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && needs.build.result == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: false
          force_orphan: true
