name: Jekyll Site CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  JEKYLL_ENV: production
  BUNDLE_PATH: vendor/bundle
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jekyll/builder:4.2.0  # Pinned version for stability
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get complete history for plugins that need it

      - name: Validate repository structure
        run: |
          echo "Repository contents:"
          ls -la
          echo "Checking required files..."
          [ -f Gemfile ] || exit 1
          [ -f _config.yml ] || exit 1
          echo "Basic structure validated"

      - name: Setup Ruby environment
        run: |
          sudo gem update --system
          sudo gem install bundler -v 2.4.22
          bundle config set path $BUNDLE_PATH
          bundle config set deployment true
          bundle config set clean true
          bundle config set without 'development test'

      - name: Install dependencies with retry
        run: |
          n=0
          until [ "$n" -ge 3 ]
          do
            bundle install --jobs 4 --retry 3 && break
            n=$((n+1))
            echo "Bundle install failed, attempt $n/3..."
            sleep 5
          done
          [ "$n" -lt 3 ] || exit 1

      - name: Verify environment
        run: |
          echo "Ruby version: $(ruby -v)"
          echo "Bundler version: $(bundle -v)"
          echo "Jekyll version: $(bundle exec jekyll -v)"
          bundle exec jekyll doctor

      - name: Build with Jekyll (with extended timeout)
        timeout-minutes: 15
        run: |
          set -exo pipefail
          bundle exec jekyll build \
            --trace \
            --verbose \
            --config _config.yml \
            --destination ./_site \
            2>&1 | tee build.log
          [ -s ./_site/index.html ] || (echo "No index.html generated" && exit 1)

      - name: Upload build logs (for debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build.log
          retention-days: 1

      - name: Upload site artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: ./_site
          retention-days: 1

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && needs.build.result == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: false
          force_orphan: true
