name: Jekyll Site CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  JEKYLL_ENV: production
  BUNDLE_PATH: vendor/bundle
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jekyll/builder:4.2.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper Git history in Jekyll

      - name: Setup Ruby environment
        run: |
          sudo apt-get update -qq
          sudo gem install bundler -v 2.4.22
          bundle config path $BUNDLE_PATH
          bundle config deployment true

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --trace --verbose
          [ -f ./_site/index.html ] || { echo "Error: No index.html generated"; exit 1; }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: ./_site
          retention-days: 1

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages  # Checkout the gh-pages branch directly
          clean: false  # Preserve existing files

      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: ./_site_temp

      - name: Prepare deployment
        run: |
          # Remove all files except .git
          if [ -d .git ]; then
            find . -path ./.git -prune -o -exec rm -rf {} \; 2> /dev/null || true
          fi
          
          # Move new files into place
          mv ./_site_temp/* .
          rm -rf ./_site_temp
          
          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config --global --add safe.directory /github/workspace

      - name: Commit and push
        run: |
          git add -A
          git commit -m "Deploy Jekyll site $(date +'%Y-%m-%d %H:%M:%S')" --allow-empty
          git push origin gh-pages
