name: Jekyll Site CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  JEKYLL_ENV: production
  BUNDLE_PATH: vendor/bundle
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jekyll/builder:4.2.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential cmake ruby-dev

      - name: Verify Ruby environment
        run: |
          echo "Ruby path: $(which ruby)"
          echo "Ruby version: $(ruby -v)"
          echo "Gem path: $(which gem)"
          gem env

      - name: Install Bundler explicitly
        run: |
          sudo gem install bundler -v 2.4.22 -N
          echo "Bundler path: $(which bundle)"

      - name: Install project dependencies
        run: |
          bundle config set path $BUNDLE_PATH
          bundle config set deployment true
          bundle install --jobs 4 --retry 3

      - name: Build with Jekyll
        run: |
          echo "Jekyll path: $(which jekyll)"
          bundle exec jekyll build --trace --verbose
          ls -la ./_site

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: ./_site
          retention-days: 1

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && needs.build.result == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: false
          force_orphan: true
