name: Jekyll Site CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  JEKYLL_ENV: production
  BUNDLE_PATH: vendor/bundle
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jekyll/builder:4.2.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate repository structure
        run: |
          echo "Repository contents:"
          ls -la
          [ -f Gemfile ] || { echo "Error: Gemfile missing"; exit 1; }
          [ -f _config.yml ] || { echo "Error: _config.yml missing"; exit 1; }

      - name: Setup Ruby environment
        run: |
          echo "Installing system dependencies..."
          sudo apt-get update -qq && sudo apt-get install -y build-essential
          echo "Updating RubyGems..."
          sudo gem update --system -N
          echo "Installing Bundler..."
          sudo gem install bundler -v 2.4.22 -N
          echo "Configuring Bundler..."
          bundle config set path $BUNDLE_PATH
          bundle config set deployment true
          bundle config set clean true
          bundle config set without 'development test'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          bundle install --jobs 4 --retry 3
          echo "Installed gems:"
          bundle list

      - name: Verify environment
        run: |
          echo "Environment versions:"
          ruby -v
          bundle -v
          bundle exec jekyll -v
          echo "Running Jekyll doctor..."
          bundle exec jekyll doctor || true

      - name: Build Jekyll site
        id: build
        run: |
          echo "Starting Jekyll build..."
          set -x
          bundle exec jekyll build \
            --trace \
            --verbose \
            --config _config.yml \
            --destination ./_site \
            > build.log 2>&1 || { echo "Jekyll build failed"; cat build.log; exit 1; }
          
          echo "Build completed successfully"
          echo "Generated files:"
          ls -la ./_site
          [ -f ./_site/index.html ] || { echo "Error: No index.html generated"; exit 1; }

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            build.log
            ./_site/.jekyll-metadata
          retention-days: 7

      - name: Upload site artifact
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: ./_site
          retention-days: 7

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && needs.build.result == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: false
          force_orphan: true
